baseURL = 'https://fritsteeuwen.github.com/'
languageCode = 'nl'
title = "Gallery"
timeZone = "Europe/Amsterdam"

[params]
  description = "Portfolio website van Frits Teeuwen"
  title = Gallerij van Frits

[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"