baseURL = 'https://fritsteeuwen.github.com/'
languageCode = 'nl'
title = "Frits Teeuwen"
timeZone = "Europe/Amsterdam"

[params]
  description = "Portfolio website van Frits"
  title = "Gallerij van Frits"

[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"